repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
    - id: cargo-format
      name: Runs cargo fmt
      entry: cargo fmt
      language: system
      pass_filenames: false
      types: [rust]
