[workspace]
resolver = "3"
members = ["crates/*"]

default-members = ["crates/inbq", "crates/inbq_genpy"]


[workspace.package]
documentation = "https://github.com/lpraat/inbq"
homepage = "https://github.com/lpraat/inbq"
repository = "https://github.com/lpraat/inbq"
readme = "README.md"
version = "0.18.0"
edition = "2024"
authors = ["Lorenzo Pratissoli <pratissolil@gmail.com>"]
license = "MIT"

[workspace.dependencies]
inbq = { version = "0.18.0", path = "crates/inbq" }
inbq_genpy = { version = "0.18.0", path = "crates/inbq_genpy"}

anyhow = "1.0.102"
bitflags = "2.11.1"
clap = { version = "4.6.1" }
env_logger = "0.11.10"
indexmap = { version = "2.14.0" }
log = "0.4.29"
serde = { version = "1.0.228" }
serde_json = "1.0.150"
strum = "0.28.0"
strum_macros = "0.28.0"
toml = "1.1.2"
pyo3 = "0.28.3"
syn = "2.0.117"
rayon = "1.12.0"
