name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt -- --check

  rs-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose


  py-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version:
          - "3.11"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./crates/py_inbq

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare venv
        run: uv sync --locked --all-extras --dev

      - name: Maturin Develop
        run: .venv/bin/maturin develop

      - name: Run tests
        run: .venv/bin/pytest python/tests
